"""Generate paper/generated/numbers.tex, one macro per quantitative claim in the text.

No number is typed by hand in the manuscript. If a statistic is missing, it is added here
rather than written into the prose.

    uv run python -m src.figtab.numbers
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

from src.analysis.panel import BUDGETS, CLASS_ORDER, DECODED, PANEL, display

DERIVED = Path("results/derived")
GEN = Path("paper/generated")

ROMAN = ["Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine"]


def _name(s: str) -> str:
    """Macro-safe name: letters only."""
    out = []
    for ch in s:
        if ch.isdigit():
            out.append(ROMAN[int(ch)])
        elif ch.isalpha():
            out.append(ch)
    return "".join(out)


class Macros:
    def __init__(self) -> None:
        self.items: dict[str, str] = {}

    def add(self, name: str, value, digits: int | None = None) -> None:
        key = _name(name)
        if isinstance(value, (int, np.integer)):
            txt = f"{int(value)}"
        elif isinstance(value, float):
            txt = "--" if not np.isfinite(value) else f"{value:.{digits if digits is not None else 2}f}"
        else:
            txt = str(value)
        self.items[key] = txt

    def write(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        lines = ["% Generated by src/figtab/numbers.py. Do not edit by hand.",
                 "% Every quantitative statement in the manuscript reads one of these macros."]
        for k, v in sorted(self.items.items()):
            lines.append(f"\\newcommand{{\\{k}}}{{{v}}}")
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"wrote {path} with {len(self.items)} macros")


def build() -> Macros:
    M = Macros()
    inst = pd.read_parquet(DERIVED / "instances.parquet")
    runs = pd.read_parquet(DERIVED / "full_runs.parquet")
    ok = runs[runs["feasible_final"].fillna(False)]
    summ = pd.read_csv(DERIVED / "summary_by_budget.csv")
    fin = summ[summ.budget_s == 300].set_index("method")
    nec = pd.read_csv(DERIVED / "necessity.csv")
    stats = json.loads((DERIVED / "stats_summary.json").read_text(encoding="utf-8"))
    pair = pd.read_csv(DERIVED / "pairwise_vs_tabu_300s.csv").set_index("method")
    transfer = json.loads((DERIVED / "transfer.json").read_text(encoding="utf-8"))
    proof = json.loads((DERIVED / "proof_model.json").read_text(encoding="utf-8"))
    abl = json.loads((DERIVED / "ablation_decoder.json").read_text(encoding="utf-8"))
    hyb = pd.read_csv(DERIVED / "hybrid_vs_pure.csv")
    hybc = pd.read_csv(DERIVED / "hybrid_cost.csv")
    sens = pd.read_csv(DERIVED / "sensitivity_population.csv").set_index("setting")
    bayes = pd.read_csv(DERIVED / "bayesian_vs_tabu.csv").set_index("right")
    cec = pd.read_parquet(DERIVED / "cec_summary.parquet")
    refmt = pd.read_csv(DERIVED / "reference_multithread.csv")

    # ---------------- design
    M.add("NInstances", len(inst))
    M.add("NJssp", int((inst.type == "JSSP").sum()))
    M.add("NFjsp", int((inst.type == "FJSP").sum()))
    M.add("NFamilies", int(inst.family.nunique()))
    M.add("MinOps", int(inst.n_op.min()))
    M.add("MaxOps", int(inst.n_op.max()))
    M.add("MedianOps", int(inst.n_op.median()))
    M.add("NMethods", len(PANEL))
    M.add("NDecoded", len(DECODED))
    M.add("NSeeds", int(ok[ok.method == "tabu"].seed.nunique()))
    M.add("Budget", 300)
    M.add("NMainRuns", len(runs))
    M.add("NHybridRuns", len(pd.read_parquet(DERIVED / "hybrid_runs.parquet")))
    M.add("NCecCells", len(cec))
    M.add("NCecFunctions", int(cec.function.nunique()))
    M.add("NCecRuns", int(cec.runs.max()))
    M.add("NCecDim", int(cec.dim.max()))
    M.add("NCecEvals", int(cec.budget_evaluations.max()))
    total = 0.0
    n_all = 0
    for stage in ("full", "hybrid", "reference", "ablation_legacy",
                  "sens_pop20", "sens_pop100", "sens_recommended"):
        d = pd.read_parquet(DERIVED / f"{stage}_runs.parquet")
        total += float(d["wall_time"].fillna(0).sum())
        n_all += len(d)
    M.add("NAllRuns", n_all)
    M.add("TotalComputeHours", total / 3600, 0)
    M.add("TotalComputeDays", total / 86400, 1)

    # ---------------- integrity
    M.add("NCrashed", int(runs.crashed.sum()))
    M.add("CrashShare", float(runs.crashed.mean() * 100), 3)
    M.add("NInfeasible", int((~runs["feasible_final"].fillna(False)).sum()))
    M.add("NRepairs", int(ok["n_repairs"].sum()))
    M.add("EvalRateMin", float(ok[ok.method.isin(DECODED)].groupby("method")["evals_per_s"]
                               .median().min()), 0)
    M.add("EvalRateMax", float(ok[ok.method.isin(DECODED)].groupby("method")["evals_per_s"]
                               .median().max()), 0)

    # ---------------- proof landscape
    ex = runs[runs.method == "cpsat"]
    proved_inst = (ex.assign(pr=(ex.status == "OPTIMAL") & (ex.wall_time <= 300))
                   .groupby("instance_id")["pr"].mean())
    M.add("NProved", int((proved_inst >= 0.5).sum()))
    M.add("ProofShare", float((proved_inst >= 0.5).mean() * 100), 1)
    for b in BUDGETS:
        pr = (ex.assign(pr=(ex.status == "OPTIMAL") & (ex.wall_time <= b))
              .groupby("instance_id")["pr"].mean() >= 0.5).sum()
        M.add(f"NProvedAt{b}", int(pr))
    j = inst.set_index("instance_id")["type"]
    pv = proved_inst >= 0.5
    M.add("NProvedJssp", int(pv[j.reindex(pv.index) == "JSSP"].sum()))
    M.add("NProvedFjsp", int(pv[j.reindex(pv.index) == "FJSP"].sum()))
    prov_time = ex[(ex.status == "OPTIMAL") & (ex.wall_time <= 300)]
    M.add("MedianProofTime", float(prov_time.groupby("instance_id")["wall_time"].median().median()), 2)
    M.add("MaxProofTime", float(prov_time["wall_time"].max()), 1)
    sizes = inst.set_index("instance_id")["n_op"]
    M.add("LargestProvedOps", int(sizes[pv[pv].index].max()))
    M.add("SmallestUnprovedOps", int(sizes[pv[~pv].index].min()))
    M.add("ProofCoefLogOps", float(proof["params"]["log_n_op"]), 2)
    M.add("ProofCoefFlex", float(proof["params"]["flex_ratio"]), 2)
    M.add("ProofOddsPerDoubling", float(np.exp(proof["params"]["log_n_op"] * np.log(2))), 3)
    M.add("ProofPseudoR", float(proof["pseudo_r2"]), 2)
    M.add("ProofPLogOps", float(proof["pvalues"]["log_n_op"]), 4)
    M.add("ProofPFlex", float(proof["pvalues"]["flex_ratio"]), 4)
    M.add("ProofStabilityLogOps", float(proof["sign_stability"]["log_n_op"]), 2)
    M.add("ProofStabilityFlex", float(proof["sign_stability"]["flex_ratio"]), 2)
    M.add("ProofStabilityMachines", float(proof["sign_stability"]["n_machines"]), 2)
    M.add("ProofStabilityDispersion", float(proof["sign_stability"]["cv_duration"]), 2)
    prov = pd.read_csv(DERIVED / "reference_provenance.csv")
    M.add("NCertifiedBks", int((prov["proven_optimal"].astype(str) == "True").sum()))
    matched = runs[(runs.method == "cpsat")].groupby("instance_id").agg(
        obj=("best_obj", "median"), bks=("bks", "first"))
    matched = matched[matched.obj <= matched.bks]
    unproved_match = [i for i in matched.index if not bool(pv.get(i, False))]
    M.add("NMatchedWithoutOwnProof", len(unproved_match))
    M.add("NMatchedWithoutOwnProofCertified",
          int(sum(1 for i in unproved_match
                  if str(prov.set_index("instance_id").loc[i, "proven_optimal"]) == "True")))
    gap = ex[ex.status != "OPTIMAL"].groupby("instance_id")["rel_gap"].median() * 100
    M.add("MedianExactGapUnproved", float(gap.median()), 1)
    M.add("MaxExactGapUnproved", float(gap.max()), 1)

    # ---------------- objective quality
    for m in PANEL:
        M.add(f"Median{_name(display(m))}", float(fin.loc[m, "median"]), 2)
        M.add(f"MeanRank{_name(display(m))}", float(fin.loc[m, "mean_rank"]), 2)
        M.add(f"NBks{_name(display(m))}", int(fin.loc[m, "n_at_bks"]))
        M.add(f"Iqr{_name(display(m))}", float(fin.loc[m, "iqr"]), 2)
    for b in BUDGETS:
        sb = summ[summ.budget_s == b].set_index("method")
        M.add(f"MedianTabuAt{b}", float(sb.loc["tabu", "median"]), 2)
        M.add(f"MedianExactAt{b}", float(sb.loc["cpsat", "median"]), 2)
        M.add(f"MedianCmaesAt{b}", float(sb.loc["cmaes", "median"]), 2)
    M.add("NInstancesAtOne", int(summ[summ.budget_s == 1]["n_instances"].iloc[0]))
    best_dec = fin.loc[DECODED, "median"].idxmin()
    M.add("BestDecodedName", display(best_dec))
    M.add("BestDecodedMedian", float(fin.loc[best_dec, "median"]), 2)
    M.add("WorstDecodedMedian", float(fin.loc[DECODED, "median"].max()), 2)
    M.add("BestDecodedRatioTabu", float(fin.loc[best_dec, "median"] / fin.loc["tabu", "median"]), 1)
    M.add("SeedIqrTabu", float(fin.loc["tabu", "seed_iqr_median"]), 2)
    M.add("SeedIqrDecodedMedian", float(fin.loc[DECODED, "seed_iqr_median"].median()), 2)

    # ---------------- omnibus and pairwise
    M.add("FriedmanStat", float(stats["cd_panel"]["friedman_stat"]), 1)
    M.add("CriticalDifference", float(stats["cd_panel"]["cd"]), 2)
    M.add("NPairwise", len(pair))
    M.add("NPairwiseSignificant", int(pair["significant"].sum()))
    M.add("TabuVsExactRbc", float(pair.loc["cpsat", "rank_biserial"]), 2)
    M.add("TabuVsExactP", float(pair.loc["cpsat", "p_holm"]), 4)
    M.add("TabuVsExactWins", int(pair.loc["cpsat", "n_wins"]))
    M.add("TabuVsExactTies", int(pair.loc["cpsat", "n_ties"]))
    others = pair.drop(index="cpsat")
    M.add("MinRbcVsTabu", float(others["rank_biserial"].min()), 2)
    M.add("MaxSuperiorityVsTabu", float(others["superiority"].max()), 3)
    M.add("NBeatTabu", int((others["superiority"] > 0).sum()))
    M.add("SaVsTabuRbc", float(pair.loc["sa", "rank_biserial"]), 2)
    M.add("RankRhoWallEval", float(stats["wallclock_vs_eval_rank_rho"]), 2)
    M.add("NProvedStratum", int(stats["n_proved_instances"]))
    for m in ("cpsat", "sa", "cmaes", "ga", "mde", "lshade", "imode", "gwo", "csa", "rime", "brkga"):
        if m in bayes.index:
            M.add(f"BayesRope{_name(display(m))}", float(bayes.loc[m, "p_rope"]), 3)
            M.add(f"BayesLeft{_name(display(m))}", float(bayes.loc[m, "p_left"]), 3)
            M.add(f"BayesRight{_name(display(m))}", float(bayes.loc[m, "p_right"]), 3)

    # ---------------- necessity
    counts = nec.groupby(["budget_s", "class"]).size().unstack(fill_value=0)
    for b in BUDGETS:
        for c in CLASS_ORDER:
            M.add(f"N{_name(c.title().replace('_', ''))}At{b}",
                  int(counts.loc[b, c]) if c in counts.columns else 0)
    sub = nec[nec.budget_s == 300]
    M.add("NRedundantAtFinal", int((sub.subclass == "1a_redundant").sum()))
    M.add("NHeuristicFasterAtFinal", int((sub.subclass == "1b_heuristic_faster").sum()))
    M.add("NStrongNecessary", int((sub.subclass == "3_strong_near_bks").sum()))
    M.add("NExactBetterAtFinal", int((sub.reason == "exact_incumbent_better").sum()))
    M.add("NExactBestObserved", int((sub["class"] == "EXACT_SUFFICIENT").sum()
                                    + (sub.reason == "exact_incumbent_better").sum()))
    M.add("ShareExactBestObserved",
          float(((sub["class"] == "EXACT_SUFFICIENT").sum()
                 + (sub.reason == "exact_incumbent_better").sum()) / len(sub) * 100), 0)
    M.add("NNecessityCells", len(nec))
    panel = pd.read_csv(DERIVED / "necessity_best_of_panel.csv")
    M.add("NTabuIsBestHeuristic", int((panel.reference_heuristic == "tabu").sum()))
    M.add("ShareTabuBest", float((panel.reference_heuristic == "tabu").mean() * 100), 0)
    necc_all = nec[nec["class"] == "HEURISTIC_NECESSARY"]
    M.add("NNecessaryCellsAll", len(necc_all))
    M.add("MedianNecessaryDominance",
          float(necc_all["delta_heuristic"].abs().median()), 2)
    M.add("MinNecessaryDominance", float(necc_all["delta_heuristic"].abs().min()), 2)
    M.add("FdrLevel", "0.05")
    nec_big = sub[sub.n_op > 500]
    M.add("NLargeInstances", len(nec_big))
    M.add("NLargeNecessary", int((nec_big["class"] == "HEURISTIC_NECESSARY").sum()))
    adv = ((sub.z_exact - sub.z_heuristic) / sub.z_exact * 100)
    M.add("MaxHeuristicAdvantage", float(adv.max()), 1)
    necc = sub[sub["class"] == "HEURISTIC_NECESSARY"]
    M.add("MedianNecessaryAdvantage",
          float(((necc.z_exact - necc.z_heuristic) / necc.z_exact * 100).median()), 1)
    M.add("MedianNecessaryOps", int(necc.n_op.median()))
    for key, label in (("delta_strict", "DeltaStrict"), ("tau_low", "TauLow"),
                       ("tau_high", "TauHigh"), ("best_of_panel", "BestOfPanel"),
                       ("cheap_hybrid", "CheapHybrid"), ("no_hybrid", "NoHybrid"),
                       ("no_fdr", "NoFdr")):
        v = pd.read_csv(DERIVED / f"necessity_{key}.csv")
        m = nec.merge(v, on=["instance_id", "budget_s"], suffixes=("", "_v"))
        M.add(f"NChanged{label}", int((m["class"] != m["class_v"]).sum()))

    # ---------------- hybrid
    for v, tag in (("hyb_cheap", "Cheap"), ("hyb_tabu", "Tabu"), ("hyb_oracle", "Oracle")):
        for b in (1, 300):
            r = hyb[(hyb.variant == v) & (hyb.budget_s == b) & (hyb.reference == "cpsat")].iloc[0]
            M.add(f"Hybrid{tag}Median{b}", float(r.median_hybrid), 2)
            M.add(f"Hybrid{tag}VsExactRbc{b}", float(r.rank_biserial), 2)
            M.add(f"Hybrid{tag}VsExactP{b}", float(r.p_holm), 4)
        c = hybc[(hybc.method == v) & (hybc.budget_s == 300)].iloc[0]
        M.add(f"Hybrid{tag}SeedTime", float(c.seed_time_median), 2)
    M.add("OraclePremiumAtOne",
          float(hyb[(hyb.variant == "hyb_tabu") & (hyb.budget_s == 1)
                    & (hyb.reference == "cpsat")].median_hybrid.iloc[0]
                - hyb[(hyb.variant == "hyb_oracle") & (hyb.budget_s == 1)
                      & (hyb.reference == "cpsat")].median_hybrid.iloc[0]), 2)

    # ---------------- transfer
    M.add("TransferRho", float(transfer["rho_wallclock"]), 2)
    M.add("TransferP", float(transfer["p_wallclock"]), 3)
    M.add("TransferCiLow", float(transfer["ci_wallclock"][0]), 2)
    M.add("TransferCiHigh", float(transfer["ci_wallclock"][1]), 2)
    M.add("TransferRhoEval", float(transfer["rho_equal_evals"]), 2)
    M.add("TransferPEval", float(transfer["p_equal_evals"]), 3)
    M.add("CecBestName", display(transfer["cec_best"][0]))
    M.add("CecSecondName", display(transfer["cec_best"][1]))
    M.add("SchedBestName", display(transfer["sched_best"][0]))
    tr = pd.read_csv(DERIVED / "transfer_ranks.csv").set_index("method")
    M.add("CecBestSchedRank", float(tr.loc[transfer["cec_best"][0], "sched_mean_rank"]), 1)
    M.add("CecBestSchedMedian", float(fin.loc[transfer["cec_best"][0], "median"]), 2)
    M.add("ImodeSchedRank", float(tr.loc["imode", "sched_mean_rank"]), 1)
    M.add("MdeCecRank", float(tr.loc["mde", "cec_mean_rank"]), 1)
    M.add("MdeSchedRank", float(tr.loc["mde", "sched_mean_rank"]), 1)

    # ---------------- decoder ablation and population policy
    M.add("AblationCells", int(abl["n_cells"]))
    M.add("AblationMedianLegacy", float(abl["median_legacy"]), 2)
    M.add("AblationMedianEligible", float(abl["median_eligible"]), 2)
    M.add("AblationDelta", float(abl["median_difference"]), 2)
    M.add("AblationRbc", float(abl["rank_biserial"]), 2)
    M.add("AblationP", float(abl["p_value"]), 4)
    M.add("AblationRepairs", float(abl["legacy_repairs_per_flexible_operation"]), 2)
    M.add("AblationWorse", int(abl["n_legacy_worse"]))
    for s, tag in (("20", "Twenty"), ("100", "Hundred"), ("recommended", "Recommended")):
        M.add(f"SensDelta{tag}", float(sens.loc[s, "median_difference_vs_common"]), 2)
        M.add(f"SensP{tag}", float(sens.loc[s, "p_value"]), 4)
        M.add(f"SensRbc{tag}", float(sens.loc[s, "rank_biserial"]), 2)

    # ---------------- multi-thread reference
    M.add("NReferenceInstances", len(refmt))
    M.add("ReferenceBudget", 900)
    M.add("NReferenceProved", int((refmt.status == "OPTIMAL").sum()))
    M.add("ReferenceMedianDeviation", float(refmt.rpd_bks.median()), 2)
    M.add("ReferenceMedianSingle", float(refmt.single_rpd.median()), 2)
    M.add("ReferenceMedianTabu", float(refmt.tabu_rpd.median()), 2)
    M.add("ReferenceBeatsTabu", int((refmt.rpd_bks < refmt.tabu_rpd).sum()))
    return M


def main() -> None:
    build().write(GEN / "numbers.tex")


if __name__ == "__main__":
    main()
